sudo: required
language: scala

jdk:
  - oraclejdk8

before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/4c2ce46242f872f3e7879810565147c4233cd52e/scripts/travis_setup.sh | bash -x

env:
  global:
    secure: "XdCqDfyq6pbm8f+CEK0jS01QSqFjs1Dsqq7Kh0O4f/d4Q82fS7eKID2WGNhqt+9/jB+q2FRgF9RPVbDnIpxrmu/G1fyFoPKT0NrpqDK8UP9dT5QntRYIyUZM/sn8F3yxlMZ/c3fyHwOG7OJFWFcFE/NJa8gkF0BFyK5HBnbR72rN0ZQS3b2NyRdgUuFvnwifwpjG6oOC10Yb0i+bFjgfcwWChmLFeL/WLse3H+ir72wUYqL53/MbBAMnPxASw8DtNuNpq342aO3W9C42wcd5/HT2q4EDysa8MgRSW7J7QAk3VJPCUSG8kG3RxPZOPC2xO+jw9qrQACpuDoFx0T/o8us830vtbvTRV2QEj+ZeiJp9O449fqW4HPFVkCVajC6Wzigrey9blT33YyI//gZFQhm1AEm91jRZxUeKsSioXHcoMA/Xlak/gZ3GsmITYpIC9v0CrU5f8CJzUUa2jwtUVzyg6l3BHW+/+QVF2T0k+TTHUf9AF1207Dho8gip5qmml8n6ov+O2WK/1alChGxfoUDsG7OpclXv2PU/U2FmO25rn+ICDVTaphcflbJ8riWevfDE+CD6wfxZvteqysWk090I66nY2upy/Jl4yH/igfGwgQr1IJSiR7Hlju5jNmqhDR8y50nr9YIZCcg5sxHw4PCWJC/npwW/hlp7RkcCW0s="

script: .ci/build

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
before_cache:
  - find $HOME/.ivy2/cache/io.crashbox -depth -name "commando*" -exec rm -r {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
