name: CI

on:
  pull_request:
  push:
      branches:
        - master
      tags:
        - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - uses: jodersky/setup-mill@master

    - name: Test
      run: mill commando.test

    - name: Publish Tag
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{secrets.GPG_KEY}}" | gpg --import
        mill mill.scalalib.PublishModule/publishAll \
          --sonatypeCreds "8VNUX6+2:${{secrets.SONATYPE_PASSWORD}}" \
          --publishArtifacts __.publishArtifacts
